repos:
- repo: https://github.com/hoefling/pre-commit-rst-lint
  rev: '0ea7c4e56416e3d38012dfcccecd35a7d95bd1dd'  # Use the sha / tag you want to point at
  hooks:
  - id: rst-lint
    additional_dependencies: [pygments]
    exclude: ^doc/.*\.rst$
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.15.0
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
# - repo: https://github.com/pre-commit/mirrors-mypy
#   rev: v1.5.1
#   hooks:
#     - id: mypy
#       verbose: true
#       exclude: ^test/testdata/
#       args: [--show-error-codes]
#       additional_dependencies: ["types-python-dateutil", "types-retry", "types-croniter", "types-click-spinner"]
